name: ESLint Static Code Analysis

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  eslint:
    name: Run ESLint and Upload SARIF
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint and generate SARIF report
        run: |
          npx eslint . --format=@microsoft/eslint-formatter-sarif --output-file=eslint-results.sarif

      - name: Upload SARIF report to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: eslint-results.sarif